---
- name: Checkout latest {{ item.repo }}
  git:
    repo: "{{ item.repo }}"
    dest: "/root/{{ item.name }}"

- name: Mirror {{ item.src_dir }}{{ item.name }} to WordPress instance {{ item.target_dir }}
  command: rsync -a --delete "/root/{{ item.src_dir  }}{{ item.name }}" "{{ wordpress_dir }}/wp-content/{{ item.target_dir }}"

- name: Fix ownership of files
  file:
    path: "{{ wordpress_dir }}/wp-content/{{ item.target_dir }}/{{ item.name }}"
    owner: www-data
    group: www-data
    recurse: yes