---
- name: Checkout latest gruenes-brett theme
  git:
    repo: "{{ gruenes_brett_repo }}"
    dest: /root/gb-theme

- name: Copy gruenes-brett theme to WordPress instance
  command: cp -a /root/gb-theme/gruenes-brett "{{ wordpress_dir }}/wp-content/themes"

- name: Fix ownership of theme
  file:
    path: "{{ wordpress_dir }}/wp-content/themes/gruenes-brett"
    owner: www-data
    group: www-data
    recurse: yes

- name: Checkout latest community-calendar plugin
  git:
    repo: "{{ community_calendar_repo }}"
    dest: /root/community-calendar

- name: Copy community-calendar plugin to WordPress instance
  command: cp -a /root/community-calendar "{{ wordpress_dir }}/wp-content/plugins"

- name: Fix ownership of plugin
  file:
    path: "{{ wordpress_dir }}/wp-content/plugins/community-calendar"
    owner: www-data
    group: www-data
    recurse: yes