---
- name: Delete unwanted pages
  include_role:
    name: wordpress/lib/delete_page
  vars:
    title: "{{ item }}"
  loop:
    - "Sample Page"
    - "Privacy Policy"

- name: Create pages
  include_role:
    name: wordpress/lib/create_page
  vars:
    title: "{{ item.title }}"
    template: "{{ item.template }}"
    parent: "{{ item.parent }}"
  with_items:
    - "{{ pages }}"
