---
- name: Delete sample-page
  include_role:
    name: wordpress/lib/delete_page
  vars:
    title: "Sample Page"

- name: Create pages
  include_role:
    name: wordpress/lib/create_page
  vars:
    title: "{{ item.title }}"
    template: "{{ item.template }}"
  with_items:
    - "{{ pages }}"
