---
- name: Create target dir {{ wordpress_dir }}
  file:
    dest: "{{ wordpress_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0770

- name: Check if WordPress is already present
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - core
      - is-installed
    do_ignore_errors: yes

- name: Download latest WordPress
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - core
      - download
      - --locale=de_DE
  when: wp_cli_result.rc == 1
