---
- name: Install msmtp
  apt:
    package:
      - msmtp
      - msmtp-mta
      - mailutils
    update_cache: yes
    cache_valid_time: 3600

- name: Write /etc/msmtprc config file
  template:
    src: msmtprc
    dest: /etc/msmtprc
    owner: root
    group: www-data
    mode: 0640

- name: Create msmtp log file
  file:
    path: /var/log/msmtp
    owner: root
    group: msmtp
    mode: 0660
    state: touch

- name: Make msmtp the default MTA
  template:
    src: mail.rc
    dest: /etc/mail.rc

- name: Restart msmtp service
  service:
    name: msmtpd
    state: restarted
