---
- name: WordPress create wp-config.php
  block:
  - name: Check if wp-config.php already exists
    stat:
      path: "{{ wordpress_dir }}/wp-config.php"
    register: wp_config_stat

  - name: Create wp-config.php
    include_role:
      name: wordpress/lib/wp-cli
    vars:
      args:
        - config
        - create
        - --dbname={{ db_name }}
        - --dbuser={{ db_user }}
        - --dbpass={{ db_password }}
    when: not wp_config_stat.stat.exists

- name: WordPress core install
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - core
      - install
      - --url={{ http_prefix }}://{{ domain }}
      - --title={{ page_title }}
      - --admin_user=admin
      - --admin_password={{ admin_password }}
      - --admin_email={{ admin_email }}

- name: Activate gruenes-brett theme
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - theme
      - activate
      - gruenes-brett

- name: Activate community-calendar plugin
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - plugin
      - activate
      - community-calendar

- name: Set permalink structure
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - rewrite
      - structure
      - '%postname%/'

- name: Flush permalink structure
  include_role:
    name: wordpress/lib/wp-cli
  vars:
    args:
      - rewrite
      - flush
