name: Cypress run

on:
  push:

  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-20.04
    container: ghcr.io/startnext/startnext-cypress:latest
    services:
      testing:
        image: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Copy node_modules within image
        run: cp /usr/app/* . -r
      - name: Make dir writable for screenshots and videos
        run: chmod o+w . -R
      - name: Run test
        run: su node -c 'bash -c "cypress run --env type=actual cypress/integration/gruenesbrett.spec.js"'
      - name: Allow downloading screenshots and videos over the GitHub interface
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: |
            cypress/snapshots
            cypress/videos
